### PR TITLE
Feature/histo validation

### PR DESCRIPTION
**Pull request by rnugent3**

### CODE REVIEW

**Review by HenryGeorgist — COMMENTED** [review]
Is the alternative compute faster now?

**Comment by rnugent3** [comment]
all of these tests failed on twos complement.

**Comment by rnugent3** [comment]
tests are sometimes passing sometimes failing on my machine

**Comment by rnugent3** [comment]
the last time tests were passing on my machine but not here I had to merge main. that is not the case this time. how else could this occur?

**Comment by rnugent3** [comment]
the work on this branch has been duplicated on another branch. closing this PR.

**Pull request closed without merging**
